# Generated by Django 6.0 on 2025-12-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/photos/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Teacher ID'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects',
            field=models.TextField(blank=True, help_text='Comma separated list of subjects', verbose_name='Subjects'),
        ),
    ]
