# Generated by Django 6.0 on 2025-12-26 14:49

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_teacherprofile_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardianprofile',
            options={'verbose_name': 'Guardian Profile', 'verbose_name_plural': 'Guardian Profiles'},
        ),
        migrations.AlterModelOptions(
            name='guardianstudentrelationship',
            options={'verbose_name': 'Guardian-Student Relationship', 'verbose_name_plural': 'Guardian-Student Relationships'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'verbose_name': 'Teacher Profile', 'verbose_name_plural': 'Teacher Profiles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_created'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='guardianprofile',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Enter middle name without numbers', max_length=50, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, dots, and apostrophes. No numbers allowed.', regex="^[A-Za-z\\s\\-\\.\\']+$"), accounts.models.validate_no_numbers], verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='guardianprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload guardian photo', null=True, upload_to='guardians/photos/', verbose_name='Guardian Photo'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Enter middle name without numbers', max_length=50, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, dots, and apostrophes. No numbers allowed.', regex="^[A-Za-z\\s\\-\\.\\']+$"), accounts.models.validate_no_numbers], verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload student photo', null=True, upload_to='students/photos/', verbose_name='Student Photo'),
        ),
        migrations.AlterField(
            model_name='guardianprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Enter complete address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='guardianprofile',
            name='guardian_id',
            field=models.CharField(help_text='Enter guardian ID', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ID can only contain letters, numbers, hyphens, and underscores.', regex='^[A-Za-z0-9\\-_]+$')], verbose_name='Guardian ID'),
        ),
        migrations.AlterField(
            model_name='guardianprofile',
            name='occupation',
            field=models.CharField(blank=True, help_text='Enter occupation/profession', max_length=100, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='guardianprofile',
            name='relation_to_student',
            field=models.CharField(help_text='e.g., Father, Mother, Guardian', max_length=50, verbose_name='Relation to Student'),
        ),
        migrations.AlterField(
            model_name='guardianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='guardianstudentrelationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Relationship Created'),
        ),
        migrations.AlterField(
            model_name='guardianstudentrelationship',
            name='guardian',
            field=models.ForeignKey(limit_choices_to={'role': 'guardian'}, on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Guardian'),
        ),
        migrations.AlterField(
            model_name='guardianstudentrelationship',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Check if this is the primary guardian', verbose_name='Primary Guardian'),
        ),
        migrations.AlterField(
            model_name='guardianstudentrelationship',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Select date of birth', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Enter emergency contact number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must contain 9-15 digits with optional '+' at the start. No letters allowed.", regex='^\\+?[0-9]{9,15}$'), accounts.models.validate_no_letters_in_phone], verbose_name='Emergency Contact'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='grade',
            field=models.CharField(blank=True, help_text='Enter grade/class', max_length=10, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, help_text='Enter section', max_length=10, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(help_text='Enter student ID', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ID can only contain letters, numbers, hyphens, and underscores.', regex='^[A-Za-z0-9\\-_]+$')], verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, help_text='Enter department name', max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='Enter designation/title', max_length=100, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Select joining date', null=True, verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Enter middle name without numbers', max_length=50, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, dots, and apostrophes. No numbers allowed.', regex="^[A-Za-z\\s\\-\\.\\']+$"), accounts.models.validate_no_numbers], verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload a professional photo', null=True, upload_to='teachers/photos/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subjects',
            field=models.TextField(blank=True, help_text='Comma separated list of subjects', verbose_name='Subjects Taught'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='ID can only contain letters, numbers, hyphens, and underscores.', regex='^[A-Za-z0-9\\-_]+$')], verbose_name='Teacher ID'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Account Created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Enter a valid email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address (e.g., user@example.com).')], verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Enter first name without numbers', max_length=30, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, dots, and apostrophes. No numbers allowed.', regex="^[A-Za-z\\s\\-\\.\\']+$"), accounts.models.validate_no_numbers], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Enter last name without numbers', max_length=30, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, dots, and apostrophes. No numbers allowed.', regex="^[A-Za-z\\s\\-\\.\\']+$"), accounts.models.validate_no_numbers], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter phone number (9-15 digits, optional +)', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must contain 9-15 digits with optional '+' at the start. No letters allowed.", regex='^\\+?[0-9]{9,15}$'), accounts.models.validate_no_letters_in_phone], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('guardian', 'Guardian')], default='student', max_length=20, verbose_name='User Role'),
        ),
    ]
