# Generated by Django 5.2.9 on 2025-12-30 02:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_guardianprofile_options_and_more'),
        ('courses', '0006_remove_subject_description_remove_subject_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, help_text="Enter student's address", verbose_name='Address'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Batch 2080, Class of 2024', max_length=100, unique=True, verbose_name='Batch Name')),
                ('description', models.TextField(blank=True, help_text='Optional description about the batch', verbose_name='Description')),
                ('year', models.IntegerField(help_text='Year when batch started (e.g., 2080)', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Batch Year')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Expected End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Batch')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-year', '-date_created'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.batch', verbose_name='Batch'),
        ),
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Enrollment Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Enrollment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='courses.course', verbose_name='Course')),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_students', to=settings.AUTH_USER_MODEL, verbose_name='Enrolled By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='accounts.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Course Enrollment',
                'verbose_name_plural': 'Student Course Enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', through='accounts.StudentCourseEnrollment', to='courses.course', verbose_name='Enrolled Courses'),
        ),
        migrations.CreateModel(
            name='BatchCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active in Batch')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_batch_courses', to=settings.AUTH_USER_MODEL, verbose_name='Added By')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_courses', to='accounts.batch', verbose_name='Batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_courses', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Batch Course',
                'verbose_name_plural': 'Batch Courses',
                'ordering': ['course__name'],
                'unique_together': {('batch', 'course')},
            },
        ),
    ]
