# Generated by Django 5.2.7 on 2025-12-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_studentprofile_address_batch_studentprofile_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='Select gender', max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(blank=True, default='Nepali', help_text='Enter nationality', max_length=50, verbose_name='Nationality'),
        ),
    ]
