# Generated by Django 5.2.7 on 2026-02-08 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_studentprofile_gender_studentprofile_nationality'),
        ('courses', '0007_alter_subject_semester_alter_subject_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('audience_type', models.CharField(choices=[('all', 'All Users'), ('batch', 'Specific Batch'), ('course', 'Specific Course'), ('role', 'Specific Role'), ('students', 'All Students'), ('teachers', 'All Teachers'), ('guardians', 'All Guardians')], default='all', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('batches', models.ManyToManyField(blank=True, related_name='notices', to='accounts.batch')),
                ('courses', models.ManyToManyField(blank=True, related_name='notices', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='noticeboard/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='noticeboard.notice')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='noticeboard.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='noticeboard.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_read_statuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoticeView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='noticeboard.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_notices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['created_at', 'is_active'], name='noticeboard_created_20355b_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['audience_type', 'created_by'], name='noticeboard_audienc_f6ce14_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['priority', 'is_important'], name='noticeboard_priorit_cbfdbe_idx'),
        ),
        migrations.AddIndex(
            model_name='noticecomment',
            index=models.Index(fields=['notice', 'created_at'], name='noticeboard_notice__301c00_idx'),
        ),
        migrations.AddIndex(
            model_name='noticecomment',
            index=models.Index(fields=['user', 'created_at'], name='noticeboard_user_id_559048_idx'),
        ),
        migrations.AddIndex(
            model_name='noticereadstatus',
            index=models.Index(fields=['user', 'is_read'], name='noticeboard_user_id_6cd627_idx'),
        ),
        migrations.AddIndex(
            model_name='noticereadstatus',
            index=models.Index(fields=['notice', 'is_read'], name='noticeboard_notice__02d8c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='noticereadstatus',
            unique_together={('notice', 'user')},
        ),
        migrations.AddIndex(
            model_name='noticeview',
            index=models.Index(fields=['notice', 'viewed_at'], name='noticeboard_notice__868599_idx'),
        ),
        migrations.AddIndex(
            model_name='noticeview',
            index=models.Index(fields=['user', 'viewed_at'], name='noticeboard_user_id_6884eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='noticeview',
            unique_together={('notice', 'user')},
        ),
    ]
