# Generated by Django 6.0 on 2025-12-26 14:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., CS101, MATH201', max_length=20, unique=True, verbose_name='Course Code')),
                ('name', models.CharField(help_text='Full name of the course', max_length=200, verbose_name='Course Name')),
                ('short_name', models.CharField(blank=True, help_text='Abbreviated name (optional)', max_length=50, verbose_name='Short Name')),
                ('description', models.TextField(blank=True, help_text='Detailed course description', verbose_name='Description')),
                ('department', models.CharField(blank=True, help_text='e.g., Computer Science, Mathematics', max_length=100, verbose_name='Department')),
                ('credit_hours', models.IntegerField(default=3, help_text='Number of credit hours (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Credit Hours')),
                ('course_type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('lab', 'Lab'), ('workshop', 'Workshop'), ('seminar', 'Seminar')], default='core', max_length=20, verbose_name='Course Type')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='Level')),
                ('semester', models.IntegerField(blank=True, help_text='Semester number (1-8)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Semester')),
                ('prerequisites', models.TextField(blank=True, help_text='List prerequisites separated by commas', verbose_name='Prerequisites')),
                ('objectives', models.TextField(blank=True, help_text='What students will learn', verbose_name='Learning Objectives')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., CS101-T, CS101-P', max_length=20, verbose_name='Subject Code')),
                ('name', models.CharField(max_length=200, verbose_name='Subject Name')),
                ('subject_type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('lab', 'Lab'), ('project', 'Project')], default='theory', max_length=20, verbose_name='Subject Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('credit_hours', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Credit Hours')),
                ('total_marks', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Total Marks')),
                ('passing_marks', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Passing Marks')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['course', 'code'],
                'unique_together': {('course', 'code')},
            },
        ),
    ]
