# Generated by Django 6.0 on 2025-12-28 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_remove_course_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['course', 'semester', 'year', 'code'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(blank=True, help_text='Required for semester-based courses (1-8)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.IntegerField(blank=True, help_text='Required for yearly-based courses (1-4)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Year'),
        ),
    ]
