# Generated by Django 6.0 on 2025-12-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_subject_options_subject_semester_subject_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='credit_hours',
        ),
    ]
