# Generated by Django 6.0 on 2025-12-28 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_subject_credit_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_taught', to=settings.AUTH_USER_MODEL, verbose_name='Subject Teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, help_text='Subject description and objectives', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='passing_marks',
            field=models.PositiveIntegerField(default=40, help_text='Minimum marks required to pass', verbose_name='Passing Marks'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_marks',
            field=models.PositiveIntegerField(default=100, help_text='Maximum marks for this subject', verbose_name='Total Marks'),
        ),
    ]
