# Generated by Django 6.0 on 2025-12-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subject_teacher_alter_subject_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='passing_marks',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_type',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='total_marks',
        ),
    ]
