# Generated by Django 6.0.1 on 2026-01-11 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_subject_description_remove_subject_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(blank=True, help_text='Choose 1-8 for semester-based courses', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(blank=True, help_text='Choose 1-4 for yearly-based courses', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Year'),
        ),
    ]
