# Generated by Django 6.0.1 on 2026-01-11 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['student__student_id'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='check_out_time',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused'), ('half_day', 'Half Day')], default='absent', max_length=20, verbose_name='Status'),
        ),
    ]
