# Generated by Django 5.2.7 on 2026-02-04 14:41

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_gender_studentprofile_nationality'),
        ('attendance', '0002_alter_attendancerecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', 'student__student_id'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date on which attendance was recorded', verbose_name='Attendance Date'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'student'], name='attendance__date_a54ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'session'], name='attendance__date_28234b_idx'),
        ),
    ]
