# Generated by Django 5.2.11 on 2026-02-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused'), ('half_day', 'Half Day')], default='absent', max_length=20, verbose_name='Status'),
        ),
    ]
